spring.application.name=api-gateway

server.port=8033


spring.main.web-application-type=reactive
# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Use IP instead of hostname (avoid underscore issue)
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Enable service discovery in Gateway

spring.cloud.gateway.discovery.locator.enabled=false
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

management.endpoints.web.exposure.include=true


# Employee Service
spring.cloud.gateway.routes[0].id=employeeservice
spring.cloud.gateway.routes[0].uri=lb://employeeservice
spring.cloud.gateway.routes[0].predicates[0]=Path=/employee/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/employee/(?<segment>.*), /${segment}

# Department Service
spring.cloud.gateway.routes[1].id=departmentservice
spring.cloud.gateway.routes[1].uri=lb://departmentservice
spring.cloud.gateway.routes[1].predicates[0]=Path=/department/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/department/(?<segment>.*), /${segment}
